### ISSUE TITLE
抓取特定使用者時失敗

### ISSUE THREAD

**Issue by lulalala** [freelze/plurk-crawler#1]
你好，感謝開發。這邊使用後抓了許多帳號都OK，不過只有下面這一個會失敗：

![252630227_3029322547302581_4610958602683695724_n](https://user-images.githubusercontent.com/366910/141681171-ff309e96-4640-45b4-bb66-0fd4c7c5f3e1.png)

**Comment by freelze** [comment]
@lulalala 你好，程式已經更新，該使用者我也測試過了。

**Comment by lulalala** [comment]
抓到了，感謝
